version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - yarn
      - yarn build
  post_build:
    commands:
      - echo $HTPASSWD_CONTENT > ./build/.htpasswd
      - aws s3 cp build s3://${BUCKET} --recursive --exclude ".git/*" --acl public-read --cache-control 'max-age=300,public'
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*"
artifacts:
  base-directory: build
  files:
    - '**/*'
